sudo: required
services:
    - docker
    
before-install:
    - docker build -t neerajkumar/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true neerajkumar/docker-react npm run test