sudo: required
services:
    - docker
    
before-install:
    - docker build -t neerajkumar/docker-react -f Dockerfile .
    
script:
    - docker run -e CI=true neerajkumar/docker-react npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-148614427631"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY